version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ricksubs-db
    environment:
      POSTGRES_DB: assinaturas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: