spring.application.name=Controle_de_Assinaturas
# Conexão com o Postgres (Mesmo servidor, banco diferente)
spring.datasource.url=jdbc:postgresql://localhost:5432/assinaturas_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Driver e Dialeto
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

api.security.token.secret=${JWT_SECRET:12345}}